[tool.poetry]
name = "aircmd"
version = "0.1.0"
description = "Extensible CLI with Click framework"
authors = ["cpdeethree <conor@airbyte.io>"]


[tool.poetry.dependencies]
python = "^3.11"
click = "^8.1.3"
mypy = "^1.2.0"
pydantic = "^1.10.7"
# uncomment for local development
airbyte-actions = {path = "../airbyte-actions", develop = true}

[tool.poetry.scripts]
aircmd = "aircmd.main:cli"

[tool.poetry.group.dev.dependencies]
ruff = "^0.0.262"
mypy = "^1.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
